- job:
    name: packaging_repoclosure
    node: el
    logrotate:
      daysToKeep: 7
      numToKeep: -1
    scm:
      - foreman-rpm-packaging
    builders:
      - packaging_repoclosure
    parameters:
      - string:
          name: repo
          default: ''
          description: "Repo on koji to test, e.g. <code>foreman-nightly</code> or <code>foreman-1.2</code>"
      - string:
          name: os
          default: el6
          description: "OS code, e.g. <code>el6</code>, <code>f18</code>"
      - string:
          name: foreman_lookasides
          default: ''
          description: "Comma separated list of published Foreman lookaside repos that exist on http://yum.theforeman.org"
      - string:
          name: koji_lookasides
          default: ''
          description: "Comma separated list of lookaside repos that exist at http://koji.katello.org/releases/yum"
      - string:
          name: copr_lookasides
          default: ''
          description: "Comma separated list of lookaside repos that exist at http://copr.fedoraproject.org/coprs"
