- job:
    name: systest_foreman_puppet
    project-type: matrix
    logrotate:
      daysToKeep: -1
      numToKeep: 3
    triggers:
      - timed: 'H 6 * * 1'
    builders:
      - trigger-builds:
        - project: systest_foreman
          predefined-parameters: "os=${os}\npl_puppet=true\nrun_puppet_tests=true"
          block: true
    axes:
      - axis:
          type: user-defined
          name: os
          values:
          - el6
          - el7
          - f19
          - wheezy
          - jessie
          - precise
          - trusty
    publishers:
      - ircbot_freenode
